//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Admin.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Admin.Test.ApiResponse", typeof(ApiResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;NAT-7&quot;,
        ///  &quot;entityId&quot;: &quot;97-159&quot;,
        ///  &quot;jiraId&quot;: null,
        ///  &quot;field&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;projectShortName&quot;,
        ///      &quot;value&quot;: &quot;NAT&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;numberInProject&quot;,
        ///      &quot;value&quot;: &quot;7&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;summary&quot;,
        ///      &quot;value&quot;: &quot;updated&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;description&quot;,
        ///      &quot;value&quot;: &quot;updated&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;created&quot;,
        ///      &quot;value&quot;: &quot;1443731565889&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;updated&quot;,
        ///      &quot;value&quot;: &quot;1444849398783&quot;
        ///    },
        ///    {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailIssueWithComments {
            get {
                return ResourceManager.GetString("DetailIssueWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;NAT-2&quot;,
        ///    &quot;entityId&quot;: &quot;97-151&quot;,
        ///    &quot;jiraId&quot;: null,
        ///    &quot;field&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;projectShortName&quot;,
        ///            &quot;value&quot;: &quot;NAT&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;numberInProject&quot;,
        ///            &quot;value&quot;: &quot;2&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;summary&quot;,
        ///            &quot;value&quot;: &quot;Admin Login&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;description&quot;,
        ///            &quot;value&quot;: &quot;testing&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;created&quot;,
        ///            &quot;value&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IssueDetail {
            get {
                return ResourceManager.GetString("IssueDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;issue&quot;: [
        ///        {
        ///            &quot;priority&quot;: &quot;3&quot;,
        ///            &quot;type&quot;: &quot;Bug&quot;,
        ///            &quot;state&quot;: &quot;Submitted&quot;,
        ///            &quot;subsystem&quot;: &quot;No Subsystem&quot;,
        ///            &quot;affectsVersion&quot;: null,
        ///            &quot;id&quot;: &quot;NAT-1&quot;,
        ///            &quot;fixedVersion&quot;: null,
        ///            &quot;projectShortName&quot;: &quot;NAT&quot;,
        ///            &quot;assigneeName&quot;: null,
        ///            &quot;reporterName&quot;: &quot;Meagan_Combs&quot;,
        ///            &quot;updaterName&quot;: &quot;Meagan_Combs&quot;,
        ///            &quot;fixedInBuild&quot;: &quot;Next build&quot;,
        ///            &quot;commentsCount&quot;: 0,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IssueList {
            get {
                return ResourceManager.GetString("IssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;NexusAdminTest&quot;,
        ///  &quot;id&quot;: &quot;NAT&quot;,
        ///  &quot;description&quot;: null,
        ///  &quot;archived&quot;: false,
        ///  &quot;lead&quot;: &quot;Meagan_Combs&quot;,
        ///  &quot;startingNumber&quot;: null,
        ///  &quot;assigneesUrl&quot;: &quot;https://yt.wolfgang.com/youtrack/rest/admin/project/NAT/assignee&quot;,
        ///  &quot;subsystemsUrl&quot;: &quot;https://yt.wolfgang.com/youtrack/rest/admin/project/NAT/subsystem&quot;,
        ///  &quot;buildsUrl&quot;: &quot;https://yt.wolfgang.com/youtrack/rest/admin/project/NAT/build&quot;,
        ///  &quot;versionsUrl&quot;: &quot;https://yt.wolfgang.com/youtrack/rest/admin/project/NAT/version&quot;
        ///}.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Admin&quot;,
        ///    &quot;defaultAssignee&quot;: &quot;&quot;,
        ///    &quot;isDefault&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Documentation&quot;,
        ///    &quot;defaultAssignee&quot;: &quot;&quot;,
        ///    &quot;isDefault&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;postmantest&quot;,
        ///    &quot;defaultAssignee&quot;: &quot;&quot;,
        ///    &quot;isDefault&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;subsystem&quot;,
        ///    &quot;defaultAssignee&quot;: &quot;&quot;,
        ///    &quot;isDefault&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Web Services&quot;,
        ///    &quot;defaultAssignee&quot;: &quot;Meagan_Combs&quot;,
        ///    &quot;isDefault&quot;: false
        ///  }
        ///].
        /// </summary>
        internal static string ProjectSubsystems {
            get {
                return ResourceManager.GetString("ProjectSubsystems", resourceCulture);
            }
        }
    }
}
